/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

/**
 *
 * @author LENOVO
 */
public class ReportView extends javax.swing.JFrame {

    /**
     * Creates new form ReportView
     */
    public ReportView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel69.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel69.setText("Total Zakat Masuk");
        jPanel1.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, -1, -1));

        jLabel70.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel70.setText("<Total Zakat Masuk>");
        jPanel1.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 620, -1, -1));

        jLabel71.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel71.setText("Total Zakat Disalurkan");
        jPanel1.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 640, -1, -1));

        jLabel72.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel72.setText("<Total Zakat Disalurkan>");
        jPanel1.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 640, -1, -1));

        jLabel73.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel73.setText("Sisa Zakat (Jika ada)");
        jPanel1.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 660, -1, -1));

        jLabel74.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel74.setText("<Sisa Zakat>");
        jPanel1.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 660, -1, -1));

        jLabel67.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel67.setText("Keterangan");
        jPanel1.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, -1, -1));

        jLabel68.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel68.setText("Bungkus");
        jPanel1.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 600, -1, -1));

        jLabel66.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel66.setText("Ringkasan Akhir");
        jPanel1.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, -1, -1));

        jLabel53.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel53.setText("<Fakir>");
        jPanel1.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, -1));

        jLabel54.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel54.setText("<Miskin>");
        jPanel1.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, -1, -1));

        jLabel55.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel55.setText("<Jumlah Muzakki>");
        jPanel1.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, -1));

        jLabel56.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel56.setText("<Muallaf>");
        jPanel1.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, -1, -1));

        jLabel57.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel57.setText("<Riqab>");
        jPanel1.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, -1, -1));

        jLabel58.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel58.setText("<Gharim>");
        jPanel1.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, -1, -1));

        jLabel59.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel59.setText("<Fii Sabilillah>");
        jPanel1.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, -1, -1));

        jLabel60.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel60.setText("<Ibnu Sabil>");
        jPanel1.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, -1, -1));

        jLabel61.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel61.setText("<Janda>");
        jPanel1.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, -1, -1));

        jLabel62.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel62.setText("<Duda>");
        jPanel1.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, -1, -1));

        jLabel63.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel63.setText("<Yatim/Piatu>");
        jPanel1.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, -1, -1));

        jLabel64.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel64.setText("<Ketua Amil>");
        jPanel1.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 510, -1, -1));

        jLabel65.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel65.setText("<Lainnya>");
        jPanel1.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 530, -1, -1));

        jLabel40.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel40.setText("<Fakir>");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        jLabel41.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel41.setText("<Miskin>");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        jLabel42.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel42.setText("<Jumlah Muzakki>");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));

        jLabel43.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel43.setText("<Muallaf>");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, -1));

        jLabel44.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel44.setText("<Riqab>");
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, -1, -1));

        jLabel45.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel45.setText("<Gharim>");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, -1));

        jLabel46.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel46.setText("<Fii Sabilillah>");
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, -1, -1));

        jLabel47.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel47.setText("<Ibnu Sabil>");
        jPanel1.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, -1, -1));

        jLabel48.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel48.setText("<Janda>");
        jPanel1.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, -1, -1));

        jLabel49.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel49.setText("<Duda>");
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, -1, -1));

        jLabel50.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel50.setText("<Yatim/Piatu>");
        jPanel1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, -1, -1));

        jLabel51.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel51.setText("<Ketua Amil>");
        jPanel1.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, -1, -1));

        jLabel52.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel52.setText("<Lainnya>");
        jPanel1.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, -1, -1));

        jLabel22.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel22.setText("Janda");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));

        jLabel23.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel23.setText("Duda");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));

        jLabel24.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel24.setText("Yatim/Piatu");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, -1, -1));

        jLabel25.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel25.setText("Ketua Amil");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, -1, -1));

        jLabel26.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel26.setText("Lainnya");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, -1, -1));

        jLabel18.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel18.setText("Riqab");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        jLabel19.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel19.setText("Gharim");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        jLabel20.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel20.setText("Fii Sabilillah");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        jLabel21.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel21.setText("Ibnu Sabil");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        jLabel16.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel16.setText("Jumlah Muzakki");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        jLabel17.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel17.setText("Muallaf");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jLabel15.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel15.setText("Miskin");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jLabel14.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel14.setText("Fakir");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLabel11.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel11.setText("Golongan Mustahiq");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel13.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel13.setText("Disalurkan  (bungkus)");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        jLabel75.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel75.setText("TOTAL");
        jPanel1.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, -1, -1));

        jLabel76.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel76.setText("<total_mustahiq>");
        jPanel1.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 550, -1, -1));

        jLabel77.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel77.setText("<total_kg>");
        jPanel1.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 550, -1, -1));

        jLabel12.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel12.setText("Jumlah Orang");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        jLabel10.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel10.setText("Penyaluran Zakat");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel7.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel7.setText("<Jumlah Muzakki>");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        jLabel9.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel9.setText("<Total Zakat Diterima>");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel8.setText("Total Zakat Diterima");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel6.setText("Jumlah Muzakki");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel3.setText("Jumlah");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel5.setText("Keterangan");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel4.setText("Penerimaan Zakat");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel2.setText("Laporan Akhir");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 270, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Background - Report.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel27.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel27.setText("Jumlah Muzakki");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jLabel28.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel28.setText("Jumlah Muzakki");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        jLabel29.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel29.setText("Jumlah Muzakki");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        jLabel30.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel30.setText("Jumlah Muzakki");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        jLabel31.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel31.setText("Jumlah Muzakki");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));

        jLabel32.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel32.setText("Jumlah Muzakki");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        jLabel33.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel33.setText("Jumlah Muzakki");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        jLabel34.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel34.setText("Jumlah Muzakki");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        jLabel35.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel35.setText("Jumlah Muzakki");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, -1));

        jLabel36.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel36.setText("Jumlah Muzakki");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, -1));

        jLabel37.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel37.setText("Jumlah Muzakki");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, -1, -1));

        jLabel38.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel38.setText("Jumlah Muzakki");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, -1, -1));

        jLabel39.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel39.setText("Jumlah Muzakki");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
