package views;

import javax.swing.JFrame;
import services.UserService;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public SignUp() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Usersign = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        pwsign2 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        phonesign = new javax.swing.JLabel();
        ulangipw = new javax.swing.JPasswordField();
        pwsign1 = new javax.swing.JLabel();
        buatpw = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        emailsign = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        createsign = new javax.swing.JButton();
        backtologin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nomorhandphone = new javax.swing.JTextField();
        pwsign3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 102));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 700));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        Usersign.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        Usersign.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Usersign.setText("Username");
        jPanel2.add(Usersign);
        Usersign.setBounds(30, 80, 77, 24);

        nama.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        jPanel2.add(nama);
        nama.setBounds(30, 180, 190, 30);

        pwsign2.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        pwsign2.setText("Ulangi Password");
        jPanel2.add(pwsign2);
        pwsign2.setBounds(30, 430, 140, 24);

        email.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel2.add(email);
        email.setBounds(30, 320, 190, 30);

        username.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel2.add(username);
        username.setBounds(30, 110, 190, 30);

        phonesign.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        phonesign.setText("Nama");
        jPanel2.add(phonesign);
        phonesign.setBounds(30, 150, 46, 24);
        jPanel2.add(ulangipw);
        ulangipw.setBounds(30, 460, 190, 30);

        pwsign1.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        pwsign1.setText("Email");
        jPanel2.add(pwsign1);
        pwsign1.setBounds(30, 290, 41, 24);
        jPanel2.add(buatpw);
        buatpw.setBounds(30, 390, 190, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("X");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel7);
        jLabel7.setBounds(300, 10, 12, 22);

        emailsign.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        emailsign.setText("Nomor Handphone");
        jPanel2.add(emailsign);
        emailsign.setBounds(30, 220, 150, 24);

        reset.setBackground(new java.awt.Color(255, 0, 0));
        reset.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        reset.setText("Reset");
        reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetMouseClicked(evt);
            }
        });
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel2.add(reset);
        reset.setBounds(30, 530, 80, 30);

        createsign.setBackground(new java.awt.Color(0, 255, 0));
        createsign.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        createsign.setText("Create");
        createsign.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createsign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createsignMouseClicked(evt);
            }
        });
        createsign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createsignActionPerformed(evt);
            }
        });
        jPanel2.add(createsign);
        createsign.setBounds(140, 530, 80, 30);

        backtologin.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        backtologin.setForeground(new java.awt.Color(51, 51, 255));
        backtologin.setText("I Have an account, Login");
        backtologin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backtologinMouseClicked(evt);
            }
        });
        jPanel2.add(backtologin);
        backtologin.setBounds(30, 560, 119, 20);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SIGN UP");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(60, 10, 160, 40);

        nomorhandphone.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        nomorhandphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomorhandphoneActionPerformed(evt);
            }
        });
        jPanel2.add(nomorhandphone);
        nomorhandphone.setBounds(30, 250, 190, 30);

        pwsign3.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        pwsign3.setText("Buat Password");
        jPanel2.add(pwsign3);
        pwsign3.setBounds(30, 360, 120, 24);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(60, 50, 290, 590);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void createsignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createsignActionPerformed
UserService userService = new UserService();
String usernameText = username.getText();
String namaText = nama.getText();
String handphoneText = nomorhandphone.getText();
String emailText = email.getText();
String passwordText = new String(buatpw.getPassword());
String ulangiPasswordText = new String(ulangipw.getPassword());


    String result = userService.signUp(usernameText, namaText, handphoneText, emailText, passwordText, ulangiPasswordText);

    if (result.equals("success")) {
        JOptionPane.showMessageDialog(this, "Akun berhasil dibuat!");
        this.dispose(); 
        LoginForm lgf = new LoginForm();
        lgf.setVisible(true);
        
    } else {
        JOptionPane.showMessageDialog(this, result);
    }
    }//GEN-LAST:event_createsignActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        username.setText("");
        nama.setText("");
        nomorhandphone.setText("");
        email.setText("");
        buatpw.setText("");
        ulangipw.setText("");
        
    }//GEN-LAST:event_resetActionPerformed

    private void backtologinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backtologinMouseClicked
        LoginForm lgf = new LoginForm();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_backtologinMouseClicked

    private void nomorhandphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomorhandphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomorhandphoneActionPerformed

    private void resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseClicked
        
        
    }//GEN-LAST:event_resetMouseClicked

    private void createsignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createsignMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_createsignMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Usersign;
    private javax.swing.JLabel backtologin;
    private javax.swing.JPasswordField buatpw;
    private javax.swing.JButton createsign;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emailsign;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nomorhandphone;
    private javax.swing.JLabel phonesign;
    private javax.swing.JLabel pwsign1;
    private javax.swing.JLabel pwsign2;
    private javax.swing.JLabel pwsign3;
    private javax.swing.JButton reset;
    private javax.swing.JPasswordField ulangipw;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
